services:
  telegram-bot:
    image: telegram-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ALLOWED_USER_IDS=${ALLOWED_USER_IDS}
      - SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
      - SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
    volumes:
      # Mount cookies if you use private/limited videos
      - /home/tolikyo/docker/igbot/Bot_IG2Telegram/cookie_instagram.txt:/app/cookie_instagram.txt:rw
      - /home/tolikyo/docker/igbot/Bot_IG2Telegram/cookie_youtube.txt:/app/cookie_youtube.txt:rw
      # Optional: persist temp if desired
      - ./temp:/app/temp
    restart: unless-stopped
